### ISSUE TITLE
Error returned in service start

### ISSUE THREAD

**Issue by ericwongmusic** [bwv1041/homebridge-mi-remote#4]
I cannot activate the plugin successfully on my homebridge config. I consulted hoobs.org, and they replied:

That’s a plugin issue. The developer must add the name of the plugin as the first parameter when registering the platform or accessory. Please open an issue with the plugin developer on their GitHub page

Please kindly fix it!  Thanks!

**Comment by bwv1041** [comment]
Please let me know your environment.

**Comment by ericwongmusic** [comment]
Thanks for the response!

I am using HOOBS to run homebridge.

Here is the config of my system:

> HOOBS Core
> Current Version: 3.2.6
> Up to Date
> Bridge Name HOOBS
> HOOBS Version 3.2.6
> Node Version 12.13.1
> Username 8D:1C:92:7E:68:CB
> Bridge Port 51826
> Home Setup PIN 031-45-154
> Home Setup ID X-HM://0023ISYWYDAM9
> Application Path /home/hoobs/.hoobs
> Configuration Path /home/hoobs/.hoobs/etc
> Local Modules Path /home/hoobs/.hoobs/node_modules
> Global Modules Path /usr/local/lib/node_modules


My json is:
        {
            "platform": "MiRemote",
            "ip": "10.0.1.42",
            "token": "97c56be5ca36a4eeffb89b69d20bf10f",
            "hideLearn": false,
            "deviceCfgs": [
                {
                    "type": "Switch",
                    "data": {
                        "Power":
"mk1mEwlk0msymEsmszmEsmM3ANKazYAgptOACLAaKazkAdgDzmoDigLwAe4A5AYRMZvMQCOBCwErwUvA48AfwMPA48JTwlPDpQBrwGqAIKYQAA=="
                    }
                }
            ]
        }



Error:
30/08/2020, 13:17:30 Error occurred: Error: Could not connect to device,
handshake timeout
30/08/2020, 13:17:30 at Timeout._onTimeout
(/home/hoobs/.hoobs/node_modules/miio/lib/network.js:427:17)
30/08/2020, 13:17:30 at listOnTimeout (internal/timers.js:531:17)
30/08/2020, 13:17:30 at processTimers (internal/timers.js:475:7) {
30/08/2020, 13:17:30 code: 'timeout',
30/08/2020, 13:17:30 device: null
30/08/2020, 13:17:30 }
30/08/2020, 13:17:30 Error occurred: Error: Could not connect to device,
handshake timeout
30/08/2020, 13:17:30 at Timeout._onTimeout
(/home/hoobs/.hoobs/node_modules/miio/lib/network.js:427:17)
30/08/2020, 13:17:30 at listOnTimeout (internal/timers.js:531:17)
30/08/2020, 13:17:30 at processTimers (internal/timers.js:475:7) {
30/08/2020, 13:17:30 code: 'timeout',
30/08/2020, 13:17:30 device: null
30/08/2020, 13:17:30 }



Kind Regards,
<http://www.gsmchoir.hk/>
Eric Wong  Music Director
www.gsmchoir.hk
94653793 <http://tel:+85294653793/>
[image: facebook] <http://facebook.com/hkweddingorganist> [image:
/a4633843-fd22-4518-ae95-b0ce21dd0b03/] <https://wa.me/85294653793> [image:
linkedin] <https://hk.linkedin.com/in/ericmusic>

**Comment by ericwongmusic** [comment]
Thanks for the response!

I am using HOOBS to run homebridge.

Here is the config of my system:

* HOOBS Core
* Current Version: 3.2.6
* Up to Date
* Bridge Name HOOBS
* HOOBS Version 3.2.6
* Node Version 12.13.1
* Username 8D:1C:92:7E:68:CB
* Bridge Port 51826
* Home Setup PIN 031-45-154
* Home Setup ID X-HM://0023ISYWYDAM9
* Application Path /home/hoobs/.hoobs
* Configuration Path /home/hoobs/.hoobs/etc
* Local Modules Path /home/hoobs/.hoobs/node_modules
* Global Modules Path /usr/local/lib/node_modules


My json is:
```
{
            "platform": "MiRemote",
            "ip": "10.0.1.42",
            "token": "97c56be5ca36a4eeffb89b69d20bf10f",
            "hideLearn": false,
            "deviceCfgs": [
                {
                    "type": "Switch",
                    "data": {
                        "Power":
"mk1mEwlk0msymEsmszmEsmM3ANKazYAgptOACLAaKazkAdgDzmoDigLwAe4A5AYRMZvMQCOBCwErwUvA48AfwMPA48JTwlPDpQBrwGqAIKYQAA=="
                    }
                }
            ]
        }
```


Error messages:
> 30/08/2020, 13:17:30 Error occurred: Error: Could not connect to device, handshake timeout
> 30/08/2020, 13:17:30 at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/miio/lib/network.js:427:17)
> 30/08/2020, 13:17:30 at listOnTimeout (internal/timers.js:531:17)
> 30/08/2020, 13:17:30 at processTimers (internal/timers.js:475:7) {
> 30/08/2020, 13:17:30 code: 'timeout',
> 30/08/2020, 13:17:30 device: null
> 30/08/2020, 13:17:30 }
> 30/08/2020, 13:17:30 Error occurred: Error: Could not connect to device, handshake timeout
> 30/08/2020, 13:17:30 at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/miio/lib/network.js:427:17)
> 30/08/2020, 13:17:30 at listOnTimeout (internal/timers.js:531:17)
> 30/08/2020, 13:17:30 at processTimers (internal/timers.js:475:7) {
> 30/08/2020, 13:17:30 code: 'timeout',
> 30/08/2020, 13:17:30 device: null
> 30/08/2020, 13:17:30 }
